name: Python package

on: [pull_request, issues]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: first time PR/issue comment
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
        pr-message: "Hi *insert username*! Congrats on making your first pull request. The *insert repo name* community welcomes you and looks forward to looking at your contribution *insert emoji*. In the meantime, please sign the CLA linked below and if you’d like, take a look at this file written for newer contributors. *link newbie doc*"