name: Climate Coach Action

on: [push]

jobs:
  climate_job:
    runs-on: ubuntu-latest
    name: A job that is scheduled once a month(S)
    steps:
    - name: Climate coach comment creation step 
      uses: pavitthrap/hci-climate-coach@v1.0.101
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        google-api-key: ${{ secrets.GOOGLE_API_KEY }}
        repo-name: "hci-demo"
        repo-owner: "pavitthrap"
        username: ${{secrets.MAIL_USERNAME}} 
        password: ${{secrets.MAIL_PASSWORD}}
        send-grid-key: ${{secrets.SEND_GRID_KEY}}
        #- name: Saving csv file
        #  uses: actions/upload-artifact@v1
        #  with:
        #    name: artifact 
        #    path: report.csv
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        # body: file://climate_report.txt
        to: 'pavittthp@andrew.cmu.edu'
        from: ' "Pavitthra Pandurangan" <pavitthra.n.p@gmail.com>'
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # Optional attachments:
         #attachments: attachments.zip,git.diff,./dist/static/main.js
