name: Climate Coach Action

on: [push]

jobs:
  climate_job:
    runs-on: ubuntu-latest
    name: A job that is scheduled once a month
    steps:
    - name: Climate coach comment creation step 
      uses: pavitthrap/hci-climate-coach@v1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-name: "hci-demo"
        repo-owner: "pavitthrap"
