name: Python package

on:
  push:
  schedule:
    - cron: '07 21 22 1-12 *'

jobs:
  moodbar_job:
    runs-on: ubuntu-latest
    name: A job that is scheduled every 15 min
    steps:
    - name: Moodbar comment creation step 
      uses: pavitthrap/hci-moodbar@v1.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-name: "hci-demo"
        moodbar-message: "# Moodbar Issue.\nThis is the message that will be displayed on users' first issue."
        mentor-list: "pavitthrap, wfaad" 
