name: Python package

on: [pull_request, issues]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: pavitthrap/hci-first-interaction@v1.6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
